// packages/autofit.js-vue/src/components/AutoFit.vue
<script setup>
import { useAutoFit } from "../hooks/useAutoFit";

const props = defineProps({
    id: {
        type: Number,
        required: true,
        default: "container",
    },
    designWidth: {
        type: Number,
        default: 1920,
    },
    designHeight: {
        type: Number,
        default: 1080,
    },
    className: String,
});

useAutoFit(props.id, {
    designWidth: props.designWidth,
    designHeight: props.designHeight,
});
</script>

<template>
    <div
        :id="id"
        :class="{ 'autoFit-js-vue-container': true, [className]: className }"
        :style="{ width: `${designWidth ?? 1920}px`, height: `${designHeight ?? 1980}px` }"
    >
        <slot></slot>
    </div>
</template>

// packages/autofit.js-react/src/components/AutoFit.tsx
import { type FC, type PropsWithChildren } from "react";
import { useAutoFit } from "../hooks/useAutoFit";

const AutoFit: FC<PropsWithChildren<{ designWidth: any; designHeight: any; className?: any; id?: any }>> = (props) => {
    const { id, className = "", ...restProps } = props;

    useAutoFit(props.id, restProps);

    return (
        <div id={id} className={`autoFit-js-vue-container ${className}`} style={{ width: restProps.designWidth, height: restProps.designHeight }}>
            {props.children}
        </div>
    );
};

AutoFit.defaultProps = {
    designWidth: 1920,
    designHeight: 1080,
};

export { AutoFit };
